# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  AzureDevOpsOrg: https://dev.azure.com/matthewwhite

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: CmdLine@2
  displayName: Enable az devops addon
  inputs:
    script: |
      az extension add --name azure-devops

- task: CmdLine@2
  displayName: az devops login
  inputs:
    script: |
      echo $AZURE_DEVOPS_EXT_PAT | az devops login --organization $(AzureDevOpsOrg)
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

- task: CmdLine@2
  displayName: Test list PRs
  inputs:
    script: |
      az repos pr list
